services:
  mysql:
    image: 'mariadb:latest'
    environment:
      - 'MYSQL_DATABASE=host'
      - 'MYSQL_PASSWORD='
      - 'MYSQL_ROOT_PASSWORD=12345'
      - 'MYSQL_USER=root'
    ports:
      - '3306'