services:
  mysql:
    container_name: 'expenseModel'
    image: 'mariadb:latest'
    environment:
      - 'MYSQL_DATABASE=localhost'
      - 'MYSQL_PASSWORD=12345'
      - 'MYSQL_ROOT_PASSWORD=12345'
      - 'MYSQL_USER=root'
    ports:
      - '3306'